### ISSUE TITLE
ImportError: cannot import name 'MetricBase' from 'fastNLP.core.metrics'

### ISSUE THREAD

**Issue by Arkadiy-Garber** [lmsac/DeepFLR#1]
Hi, I am getting this error after following the user_guide instructions exactly (which I did):

```
(deepfmt) ark@TheBelly:~/bin/DeepFLR$ python3 replace.py --do_decoy --no_target --inputfile demo_data/mono_target_decoy_msms_sample.csv 
Traceback (most recent call last):
  File "replace.py", line 1, in <module>
    from model import *
  File "/home/ark/bin/DeepFLR/model.py", line 11, in <module>
    from fastNLP.core.metrics import MetricBase,seq_len_to_mask
ImportError: cannot import name 'MetricBase' from 'fastNLP.core.metrics' (/home/ark/.local/lib/python3.8/site-packages/fastNLP/core/metrics/__init__.py)
```

Thanks,
Arkadiy

**Comment by yuz2011** [comment]
Hi,
You could first ensure that the correct version of FastNLP is installed in your environment. You can run the following command to check the currently installed version of FastNLP:
pip show fastNLP
If the version is not 0.6.0, you need to install the correct version.
If the problem persists after installing the correct version, please let me know.

Best,
Yu

**Comment by Arkadiy-Garber** [comment]
This is the output from running that command:

```
(deepfmt) ark@TheBelly:~$ pip show fastNLP
Name: FastNLP
Version: 1.0.1
Summary: fastNLP: Deep Learning Toolkit for NLP, developed by Fudan FastNLP Team
Home-page: https://gitee.com/fastnlp/fastNLP
Author: Fudan FastNLP Team
Author-email: None
License: Apache License
Location: /home/ark/.local/lib/python3.8/site-packages
Requires: rich, packaging, numpy, regex, prettytable, requests
Required-by: 
```

I just followed the installation instructions provided here: [https://github.com/lmsac/DeepFLR/blob/main/User%20guide.docx](https://github.com/lmsac/DeepFLR/blob/main/User%20guide.docx)

**Comment by Arkadiy-Garber** [comment]
I also ran the following:

```
(deepfmt) ark@TheBelly:~$ pip install fastNLP --upgrade
Requirement already up-to-date: fastNLP in ./.local/lib/python3.8/site-packages (1.0.1)
Requirement already satisfied, skipping upgrade: packaging in ./.local/lib/python3.8/site-packages (from fastNLP) (24.0)
Requirement already satisfied, skipping upgrade: numpy>=1.14.2 in ./.local/lib/python3.8/site-packages (from fastNLP) (1.24.4)
Requirement already satisfied, skipping upgrade: rich==11.2.0 in ./.local/lib/python3.8/site-packages (from fastNLP) (11.2.0)
Requirement already satisfied, skipping upgrade: regex!=2019.12.17 in ./.local/lib/python3.8/site-packages (from fastNLP) (2023.12.25)
Requirement already satisfied, skipping upgrade: requests in /usr/lib/python3/dist-packages (from fastNLP) (2.22.0)
Requirement already satisfied, skipping upgrade: prettytable>=0.7.2 in ./.local/lib/python3.8/site-packages (from fastNLP) (3.10.0)
Requirement already satisfied, skipping upgrade: pygments<3.0.0,>=2.6.0 in ./.local/lib/python3.8/site-packages (from rich==11.2.0->fastNLP) (2.17.2)
Requirement already satisfied, skipping upgrade: commonmark<0.10.0,>=0.9.0 in ./.local/lib/python3.8/site-packages (from rich==11.2.0->fastNLP) (0.9.1)
Requirement already satisfied, skipping upgrade: colorama<0.5.0,>=0.4.0 in /usr/lib/python3/dist-packages (from rich==11.2.0->fastNLP) (0.4.3)
Requirement already satisfied, skipping upgrade: wcwidth in /usr/lib/python3/dist-packages (from prettytable>=0.7.2->fastNLP) (0.1.8)
```

**Comment by yuz2011** [comment]
Hi,
As I have mentioned before, If the version is not 0.6.0, you need to install the correct version.
Additionally, the User Guide also specifies FastNLP (0.6.0) as the required version.
I believe it would be beneficial to switch to the tested version first to avoid any potential issues. 

Best,
Yu

**Comment by Arkadiy-Garber** [comment]
Hi Yu,

Ok, I thought that running `pip install fastNLP` would give me the most up-to-date version, but looks like that was a misunderstanding on my end. I did re-install the software specifying version 0.6.0:

```
(deepfmt) ark@TheBelly:~/bin/DeepFLR$ pip show fastNLP
Name: FastNLP
Version: 0.6.0
Summary: fastNLP: Deep Learning Toolkit for NLP, developed by Fudan FastNLP Team
Home-page: https://github.com/fastnlp/fastNLP
Author: FudanNLP
Author-email: None
License: Apache License
Location: /home/ark/.local/lib/python3.8/site-packages
Requires: prettytable, spacy, requests, regex, torch, tqdm, numpy
Required-by: 
(deepfmt) ark@TheBelly:~/bin/DeepFLR$ 
```

The script seems to have successfully progressed past the error I mentioned before, and now is producing the following output, which looks more promising, but is still, unfortunately, crashing out:

```
(deepfmt) ark@TheBelly:~/bin/DeepFLR$ python3 replace.py --do_decoy --no_target --inputfile demo_data/mono_target_decoy_msms_sample.csv 
+-------------+--------+------+----------------+-----+--------------------+----------------+---------+-------------+---------------+--------------------+
| peptide     | charge | ions | decoration     | irt | peptide_tokens     | peptide_length | pnumber | target      | input_ids     | decoration_ids     |
+-------------+--------+------+----------------+-----+--------------------+----------------+---------+-------------+---------------+--------------------+
| ADEPSSEE... | 2      | 0    | [0, 0, 0, 0... | 0   | [6, 8, 4, 3, 2,... | 15             | 1       | [0. 0. 0... | [22, 6, 23... | [0, 0, 0, 0, 0,... |
| ADEPSSEE... | 2      | 1    | [0, 0, 0, 0... | 1   | [6, 8, 4, 3, 2,... | 15             | 1       | [0. 0. 0... | [22, 6, 23... | [0, 0, 0, 0, 0,... |
| ADEPSSEE... | 2      | 2    | [0, 0, 0, 0... | 2   | [6, 8, 4, 3, 2,... | 15             | 1       | [0. 0. 0... | [22, 6, 23... | [0, 0, 0, 0, 0,... |
| ADEPLSEE... | 2      | 3    | [0, 0, 0, 0... | 3   | [6, 8, 4, 3, 5,... | 15             | 1       | [0. 0. 0... | [22, 6, 23... | [0, 0, 0, 0, 0,... |
| ADESSPEE... | 2      | 4    | [0, 0, 0, 1... | 4   | [6, 8, 4, 2, 2,... | 15             | 1       | [0. 0. 0... | [22, 6, 23... | [0, 0, 0, 0, 0,... |
| ADEPSSEE... | 2      | 5    | [0, 0, 0, 0... | 5   | [6, 8, 4, 3, 2,... | 15             | 1       | [0. 0. 0... | [22, 6, 23... | [0, 0, 0, 0, 0,... |
| ADEPSSEE... | 3      | 6    | [0, 0, 0, 0... | 6   | [6, 8, 4, 3, 2,... | 15             | 1       | [0. 0. 0... | [22, 6, 23... | [0, 0, 0, 0, 0,... |
| ADEPSSEE... | 3      | 7    | [0, 0, 0, 0... | 7   | [6, 8, 4, 3, 2,... | 15             | 1       | [0. 0. 0... | [22, 6, 23... | [0, 0, 0, 0, 0,... |
| ADEPSSEE... | 3      | 8    | [0, 0, 0, 0... | 8   | [6, 8, 4, 3, 2,... | 15             | 1       | [0. 0. 0... | [22, 6, 23... | [0, 0, 0, 0, 0,... |
| ADEPESSE... | 3      | 9    | [0, 0, 0, 0... | 9   | [6, 8, 4, 3, 4,... | 15             | 1       | [0. 0. 0... | [22, 6, 23... | [0, 0, 0, 0, 0,... |
| ADEPSEES... | 3      | 10   | [0, 0, 0, 0... | 10  | [6, 8, 4, 3, 2,... | 15             | 1       | [0. 0. 0... | [22, 6, 23... | [0, 0, 0, 0, 0,... |
| ADEPSSEE... | 3      | 11   | [0, 0, 0, 0... | 11  | [6, 8, 4, 3, 2,... | 15             | 1       | [0. 0. 0... | [22, 6, 23... | [0, 0, 0, 0, 0,... |
| ADEPSSEE... | 2      | 12   | [0, 0, 0, 0... | 12  | [6, 8, 4, 3, 2,... | 15             | 1       | [0. 0. 0... | [22, 6, 23... | [0, 0, 0, 0, 0,... |
| ADEPSSEE... | 2      | 13   | [0, 0, 0, 0... | 13  | [6, 8, 4, 3, 2,... | 15             | 1       | [0. 0. 0... | [22, 6, 23... | [0, 0, 0, 0, 0,... |
| ADEPSSEE... | 2      | 14   | [0, 0, 0, 0... | 14  | [6, 8, 4, 3, 2,... | 15             | 1       | [0. 0. 0... | [22, 6, 23... | [0, 0, 0, 0, 0,... |
| ADEPLSEE... | 2      | 15   | [0, 0, 0, 0... | 15  | [6, 8, 4, 3, 5,... | 15             | 1       | [0. 0. 0... | [22, 6, 23... | [0, 0, 0, 0, 0,... |
| ASEPSDEE... | 2      | 16   | [0, 1, 0, 0... | 16  | [6, 2, 4, 3, 2,... | 15             | 1       | [0. 0. 0... | [22, 6, 23... | [0, 0, 0, 1, 0,... |
| ADESSSEE... | 2      | 17   | [0, 0, 0, 1... | 17  | [6, 8, 4, 2, 2,... | 15             | 1       | [0. 0. 0... | [22, 6, 23... | [0, 0, 0, 0, 0,... |
| ADEPSSEE... | 2      | 18   | [0, 0, 0, 0... | 18  | [6, 8, 4, 3, 2,... | 15             | 1       | [0. 0. 0... | [22, 6, 23... | [0, 0, 0, 0, 0,... |
| ADEPSSEE... | 2      | 19   | [0, 0, 0, 0... | 19  | [6, 8, 4, 3, 2,... | 15             | 1       | [0. 0. 0... | [22, 6, 23... | [0, 0, 0, 0, 0,... |
| ADEPSSEE... | 2      | 20   | [0, 0, 0, 0... | 20  | [6, 8, 4, 3, 2,... | 15             | 1       | [0. 0. 0... | [22, 6, 23... | [0, 0, 0, 0, 0,... |
| ASEPDSEE... | 2      | 21   | [0, 1, 0, 0... | 21  | [6, 2, 4, 3, 8,... | 15             | 1       | [0. 0. 0... | [22, 6, 23... | [0, 0, 0, 1, 0,... |
| ADEPSEES... | 2      | 22   | [0, 0, 0, 0... | 22  | [6, 8, 4, 3, 2,... | 15             | 1       | [0. 0. 0... | [22, 6, 23... | [0, 0, 0, 0, 0,... |
| ADEPSSEE... | 2      | 23   | [0, 0, 0, 0... | 23  | [6, 8, 4, 3, 2,... | 15             | 1       | [0. 0. 0... | [22, 6, 23... | [0, 0, 0, 0, 0,... |
| ADEPSSEE... | 2      | 24   | [0, 0, 0, 0... | 24  | [6, 8, 4, 3, 2,... | 15             | 1       | [0. 0. 0... | [22, 6, 23... | [0, 0, 0, 0, 0,... |
| ADEPSSEE... | 2      | 25   | [0, 0, 0, 0... | 25  | [6, 8, 4, 3, 2,... | 15             | 1       | [0. 0. 0... | [22, 6, 23... | [0, 0, 0, 0, 0,... |
| ADEPSSEE... | 2      | 26   | [0, 0, 0, 0... | 26  | [6, 8, 4, 3, 2,... | 15             | 1       | [0. 0. 0... | [22, 6, 23... | [0, 0, 0, 0, 0,... |
| ADESPSEE... | 2      | 27   | [0, 0, 0, 1... | 27  | [6, 8, 4, 2, 3,... | 15             | 1       | [0. 0. 0... | [22, 6, 23... | [0, 0, 0, 0, 0,... |
| SDEPSAEE... | 2      | 28   | [1, 0, 0, 0... | 28  | [2, 8, 4, 3, 2,... | 15             | 1       | [0. 0. 0... | [22, 2, 23... | [0, 1, 0, 0, 0,... |
| ADEPSSEE... | 2      | 29   | [0, 0, 0, 0... | 29  | [6, 8, 4, 3, 2,... | 15             | 1       | [0. 0. 0... | [22, 6, 23... | [0, 0, 0, 0, 0,... |
| ...         | ...    | ...  | ...            | ... | ...                | ...            | ...     | ...         | ...           | ...                |
+-------------+--------+------+----------------+-----+--------------------+----------------+---------+-------------+---------------+--------------------+
config.json: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 570/570 [00:00<00:00, 44.2kB/s]
Traceback (most recent call last):
  File "replace.py", line 175, in <module>
    bestmodel=torch.load(bestmodelpath).state_dict()
  File "/home/ark/.local/lib/python3.8/site-packages/torch/serialization.py", line 998, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/ark/.local/lib/python3.8/site-packages/torch/serialization.py", line 445, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/ark/.local/lib/python3.8/site-packages/torch/serialization.py", line 426, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'phosT/best__2deepchargeModelms2_bert_mediancos_2021-09-20-01-17-50-729399'
```

Please advise on how to proceed.

Thanks,
Arkadiy

**Comment by yuz2011** [comment]
Hi,
![image](https://github.com/lmsac/DeepFLR/assets/106479481/861a0fd6-1045-4275-b5f1-7ca52a0662eb)
It is specified here.

Best,
Yu

**Comment by Arkadiy-Garber** [comment]
Ok, great. Thank you, that worked.

Just moving through the demo data, here's the next issue:

```
(deepfmt) ark@TheBelly:~/bin/DeepFLR$ python3 result_processing/DeepFLR_result_processing.py --modelresultfile demo_data/mono_target_decoy_msms_samplemodelmonomz_modelresult.csv --inputfile1 demo_data/msms_sample.txt --inputfile2 demo_data/Phospho_STY_Sites.txt --sequencefile demo_data/mono_target_decoy_msms_sample.csv --cutoff 0 --outputresult demo_data/DeepFLR_phosphosites_obtained_sample.csv 
                                   SourceFile  Spectrum                          PP.PIMID  ...                                                 mz  Tintensity           score
0   20190215_QE7_nLC3_ChKe_SA_SigmaMix5_DDA_1      7108  _ADEPS[Phospho (STY)]SEESDLEIDK_  ...  [100.9736862, 102.0554504, 110.0718689, 115.08...         0.0  tensor(0.6651)
1   20190215_QE7_nLC3_ChKe_SA_SigmaMix5_DDA_1      7108  _ADEPSS[Phospho (STY)]EESDLEIDK_  ...  [100.9736862, 102.0554504, 110.0718689, 115.08...         0.0  tensor(0.6263)
2   20190215_QE7_nLC3_ChKe_SA_SigmaMix5_DDA_1      7108  _ADEPSSEES[Phospho (STY)]DLEIDK_  ...  [100.9736862, 102.0554504, 110.0718689, 115.08...         0.0  tensor(0.5372)
3   20190215_QE7_nLC3_ChKe_SA_SigmaMix5_DDA_1      7108  _ADEPLSEESDS[Phospho (STY)]EIDK_  ...  [100.9736862, 102.0554504, 110.0718689, 115.08...         0.0  tensor(0.3665)
4   20190215_QE7_nLC3_ChKe_SA_SigmaMix5_DDA_1      7108  _ADES[Phospho (STY)]SPEESDLEIDK_  ...  [100.9736862, 102.0554504, 110.0718689, 115.08...         0.0  tensor(0.4724)
5   20190215_QE7_nLC3_ChKe_SA_SigmaMix5_DDA_1      7108  _ADEPSSEEEDLS[Phospho (STY)]IDK_  ...  [100.9736862, 102.0554504, 110.0718689, 115.08...         0.0  tensor(0.3884)
6   20190215_QE7_nLC3_ChKe_SA_SigmaMix5_DDA_1      7716  _ADEPS[Phospho (STY)]SEESDLEIDK_  ...  [101.0713196, 102.0554504, 104.0534515, 110.07...         0.0  tensor(0.5536)
7   20190215_QE7_nLC3_ChKe_SA_SigmaMix5_DDA_1      7716  _ADEPSS[Phospho (STY)]EESDLEIDK_  ...  [101.0713196, 102.0554504, 104.0534515, 110.07...         0.0  tensor(0.5197)
8   20190215_QE7_nLC3_ChKe_SA_SigmaMix5_DDA_1      7716  _ADEPSSEES[Phospho (STY)]DLEIDK_  ...  [101.0713196, 102.0554504, 104.0534515, 110.07...         0.0  tensor(0.6530)
9   20190215_QE7_nLC3_ChKe_SA_SigmaMix5_DDA_1      7716  _ADEPESS[Phospho (STY)]ESDLEIDK_  ...  [101.0713196, 102.0554504, 104.0534515, 110.07...         0.0  tensor(0.5361)
10  20190215_QE7_nLC3_ChKe_SA_SigmaMix5_DDA_1      7716  _ADEPSEES[Phospho (STY)]SDLEIDK_  ...  [101.0713196, 102.0554504, 104.0534515, 110.07...         0.0  tensor(0.5309)
11  20190215_QE7_nLC3_ChKe_SA_SigmaMix5_DDA_1      7716  _ADEPSSEEEDLS[Phospho (STY)]IDK_  ...  [101.0713196, 102.0554504, 104.0534515, 110.07...         0.0  tensor(0.5183)
12  20190215_QE7_nLC3_ChKe_SA_SigmaMix5_DDA_1      7736  _ADEPS[Phospho (STY)]SEESDLEIDK_  ...  [102.0554657, 115.0870056, 116.0709763, 123.75...         0.0  tensor(0.5151)
13  20190215_QE7_nLC3_ChKe_SA_SigmaMix5_DDA_1      7736  _ADEPSS[Phospho (STY)]EESDLEIDK_  ...  [102.0554657, 115.0870056, 116.0709763, 123.75...         0.0  tensor(0.5203)
14  20190215_QE7_nLC3_ChKe_SA_SigmaMix5_DDA_1      7736  _ADEPSSEES[Phospho (STY)]DLEIDK_  ...  [102.0554657, 115.0870056, 116.0709763, 123.75...         0.0  tensor(0.6602)
15  20190215_QE7_nLC3_ChKe_SA_SigmaMix5_DDA_1      7736  _ADEPLSEESDS[Phospho (STY)]EIDK_  ...  [102.0554657, 115.0870056, 116.0709763, 123.75...         0.0  tensor(0.3649)
16  20190215_QE7_nLC3_ChKe_SA_SigmaMix5_DDA_1      7736  _AS[Phospho (STY)]EPSDEESDLEIDK_  ...  [102.0554657, 115.0870056, 116.0709763, 123.75...         0.0  tensor(0.3042)
17  20190215_QE7_nLC3_ChKe_SA_SigmaMix5_DDA_1      7736  _ADES[Phospho (STY)]SSEEPDLEIDK_  ...  [102.0554657, 115.0870056, 116.0709763, 123.75...         0.0  tensor(0.2778)
18  20190215_QE7_nLC3_ChKe_SA_SigmaMix5_DDA_1      8107  _ADEPS[Phospho (STY)]SEESDLEIDK_  ...  [101.0716248, 102.0555344, 110.071785, 115.087...         0.0  tensor(0.5944)
19  20190215_QE7_nLC3_ChKe_SA_SigmaMix5_DDA_1      8107  _ADEPSS[Phospho (STY)]EESDLEIDK_  ...  [101.0716248, 102.0555344, 110.071785, 115.087...         0.0  tensor(0.5465)
20  20190215_QE7_nLC3_ChKe_SA_SigmaMix5_DDA_1      8107  _ADEPSSEES[Phospho (STY)]DLEIDK_  ...  [101.0716248, 102.0555344, 110.071785, 115.087...         0.0  tensor(0.5006)
21  20190215_QE7_nLC3_ChKe_SA_SigmaMix5_DDA_1      8107  _AS[Phospho (STY)]EPDSEESDLEIDK_  ...  [101.0716248, 102.0555344, 110.071785, 115.087...         0.0  tensor(0.4846)
22  20190215_QE7_nLC3_ChKe_SA_SigmaMix5_DDA_1      8107  _ADEPSEES[Phospho (STY)]SDLEIDK_  ...  [101.0716248, 102.0555344, 110.071785, 115.087...         0.0  tensor(0.4918)
23  20190215_QE7_nLC3_ChKe_SA_SigmaMix5_DDA_1      8107  _ADEPSSEEDS[Phospho (STY)]LEIDK_  ...  [101.0716248, 102.0555344, 110.071785, 115.087...         0.0  tensor(0.4661)
24  20190215_QE7_nLC3_ChKe_SA_SigmaMix5_DDA_1      8499  _ADEPS[Phospho (STY)]SEESDLEIDK_  ...  [102.0554352, 110.0714493, 115.0870285, 116.07...         0.0  tensor(0.6242)
25  20190215_QE7_nLC3_ChKe_SA_SigmaMix5_DDA_1      8499  _ADEPSS[Phospho (STY)]EESDLEIDK_  ...  [102.0554352, 110.0714493, 115.0870285, 116.07...         0.0  tensor(0.5982)
26  20190215_QE7_nLC3_ChKe_SA_SigmaMix5_DDA_1      8499  _ADEPSSEES[Phospho (STY)]DLEIDK_  ...  [102.0554352, 110.0714493, 115.0870285, 116.07...         0.0  tensor(0.5557)
27  20190215_QE7_nLC3_ChKe_SA_SigmaMix5_DDA_1      8499  _ADES[Phospho (STY)]PSEESDLEIDK_  ...  [102.0554352, 110.0714493, 115.0870285, 116.07...         0.0  tensor(0.4998)
28  20190215_QE7_nLC3_ChKe_SA_SigmaMix5_DDA_1      8499  _S[Phospho (STY)]DEPSAEESDLEIDK_  ...  [102.0554352, 110.0714493, 115.0870285, 116.07...         0.0  tensor(0.3630)
29  20190215_QE7_nLC3_ChKe_SA_SigmaMix5_DDA_1      8499  _ADEPSSEEIDLES[Phospho (STY)]DK_  ...  [102.0554352, 110.0714493, 115.0870285, 116.07...         0.0  tensor(0.3614)

[30 rows x 27 columns]
   Fspectrum                                 SourceFile           Peptide       0
0       7108  20190215_QE7_nLC3_ChKe_SA_SigmaMix5_DDA_1  ADEPSS1EESDLEIDK  0.0388
1       7716  20190215_QE7_nLC3_ChKe_SA_SigmaMix5_DDA_1  ADEPSSEES1DLEIDK  0.0994
2       7736  20190215_QE7_nLC3_ChKe_SA_SigmaMix5_DDA_1  ADEPSSEES1DLEIDK  0.1399
3       8107  20190215_QE7_nLC3_ChKe_SA_SigmaMix5_DDA_1  ADEPS1SEESDLEIDK  0.0479
4       8499  20190215_QE7_nLC3_ChKe_SA_SigmaMix5_DDA_1  ADEPS1SEESDLEIDK  0.0260
(0, 8)
(5, 8)
(5, 8)
5
5
5
5.0
5.0
5
5
nan
nan
5
9.0
9.0
5
9
5.0
5.0
9
9
nan
nan
9
9.0
9.0
9
9
5.0
5.0
9
9
nan
nan
9
9.0
9.0
9
5
5.0
5.0
5
5
nan
nan
5
9.0
9.0
5
5
5.0
5.0
5
5
nan
nan
5
9.0
9.0
5
Traceback (most recent call last):
  File "result_processing/DeepFLR_result_processing.py", line 191, in <module>
    df["model_proteinsite"]=df.apply(combine,axis=1)
  File "/home/ark/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 3940, in __setitem__
    self._set_item_frame_value(key, value)
  File "/home/ark/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 4094, in _set_item_frame_value
    raise ValueError(
ValueError: Cannot set a DataFrame with multiple columns to the single column model_proteinsite
```

It looks like a table was generated beore the ValueError was raised. Any thoughts on whether this is a serious issue?

Thanks,
Arkadiy

**Comment by yuz2011** [comment]
Hi Arkadiy,
Thank you for your message. I have successfully executed the code on my end without encountering any issues. If it is convenient for you, could you please provide me with the input files or any additional relevant details? This would allow me to replicate the conditions under which you experienced the problem and better assist you in debugging.
![image](https://github.com/lmsac/DeepFLR/assets/106479481/5989878d-48dd-4c2d-a3e6-d5fcb37aa233)

As I am currently approaching a deadline for a research project, It may take a certain amount of time but I will ensure to address this matter and respond to you within the next one or two weeks.

Best,
Yu

**Comment by Arkadiy-Garber** [comment]
Ok, sounds good, thanks. I am attaching here the demo folder that I've been working out of.

Here are the commands that I ran successfully so far:


`python3 sequence_generation/Targetdecoy_phosphopeptides_generation_mono.py --inputfile demo_data/msms_sample.txt --outputfile demo_data/mono_target_decoy_msms_sample.csv`


`python3 replace.py --do_decoy --no_target --inputfile demo_data/mono_target_decoy_msms_sample.csv
`

`python3 mgfprocess.py --ppm 25 --do_mgfprocess --do_scoreprediction --inputfile demo_data/mono_target_decoy_msms_samplemodelmonomz.csv --outputfile demo_data/mono_target_decoy_msms_samplemodelmonomz_modelresult.csv --mgfdatafold demo_data
`

`python3 result_processing/DeepFLR_FLR_visualization.py --modelresultfile demo_data/mono_target_decoy_msms_samplemodelmonomz_modelresult.csv --sequencefile demo_data/mono_target_decoy_msms_sample.csv --outputfile demo_data/FLRPSM_demo.csv 
`

`python3 result_processing/DeepFLR_result_processing.py --modelresultfile demo_data/mono_target_decoy_msms_samplemodelmonomz_modelresult.csv --inputfile1 demo_data/msms_sample.txt --inputfile2 demo_data/Phospho_STY_Sites.txt --sequencefile demo_data/mono_target_decoy_msms_sample.csv --cutoff 0 --outputresult demo_data/DeepFLR_phosphosites_obtained_sample.csv`

And here's a list of python packages installed in that conda env that I'm using for this:

```
Package                  Version             
------------------------ --------------------
annotated-types          0.6.0               
apturl                   0.5.2               
atomicwrites             1.1.5               
attrs                    19.3.0              
Automat                  0.8.0               
bcrypt                   3.1.7               
beautifulsoup4           4.8.2               
bidict                   0.23.1              
biopython                1.79                
blinker                  1.4                 
blis                     0.7.11              
Brlapi                   0.7.0               
CacheControl             0.12.6              
catalogue                2.0.10              
certifi                  2019.11.28          
chardet                  3.0.4               
click                    8.1.7               
cloud-init               23.1.2              
cloudpathlib             0.16.0              
colorama                 0.4.3               
coloredlogs              7.3                 
command-not-found        0.3                 
commonmark               0.9.1               
confection               0.1.4               
configobj                5.0.6               
constantly               15.1.0              
cryptography             2.8                 
cupshelpers              1.0                 
cutadapt                 2.8                 
cwltool                  2.0.20200224214940  
cymem                    2.0.8               
dbus-python              1.2.16              
decorator                4.4.2               
defer                    1.0.6               
distro                   1.4.0               
distro-info              0.23ubuntu1         
dnaio                    0.4.1               
duplicity                0.8.12.0            
entrypoints              0.3                 
fasteners                0.14.1              
FastNLP                  0.6.0               
filelock                 3.13.4              
fq2fa                    1.1                 
fsspec                   2024.3.1            
future                   0.18.2              
html5lib                 1.0.1               
HTSeq                    0.11.2              
httplib2                 0.14.0              
huggingface-hub          0.22.2              
humanfriendly            4.18                
hyperlink                19.0.0              
idna                     2.8                 
importlib-metadata       1.5.0               
incremental              16.10.1             
isodate                  0.6.0               
Jinja2                   2.10.1              
joblib                   0.14.0              
jsonpatch                1.22                
jsonpointer              2.0                 
jsonschema               3.2.0               
keyring                  18.0.1              
langcodes                3.3.0               
language-selector        0.1                 
launchpadlib             1.10.13             
lazr.restfulclient       0.14.2              
lazr.uri                 1.0.3               
lockfile                 0.12.2              
louis                    3.12.0              
lxml                     4.5.0               
macaroonbakery           1.3.1               
Mako                     1.1.0               
MarkupSafe               1.1.0               
mistune                  0.8.4               
monotonic                1.5                 
more-itertools           4.2.0               
mpmath                   1.3.0               
msgpack                  0.6.2               
murmurhash               1.0.10              
mypy-extensions          0.4.3               
netifaces                0.10.4              
networkx                 2.4                 
numpy                    1.24.4              
nvidia-cublas-cu12       12.1.3.1            
nvidia-cuda-cupti-cu12   12.1.105            
nvidia-cuda-nvrtc-cu12   12.1.105            
nvidia-cuda-runtime-cu12 12.1.105            
nvidia-cudnn-cu12        8.9.2.26            
nvidia-cufft-cu12        11.0.2.54           
nvidia-curand-cu12       10.3.2.106          
nvidia-cusolver-cu12     11.4.5.107          
nvidia-cusparse-cu12     12.1.0.106          
nvidia-nccl-cu12         2.19.3              
nvidia-nvjitlink-cu12    12.4.127            
nvidia-nvtx-cu12         12.1.105            
oauthlib                 3.1.0               
olefile                  0.46                
packaging                24.0                
pandas                   2.0.3               
paramiko                 2.6.0               
pexpect                  4.6.0               
Pillow                   7.0.0               
pip                      20.0.2              
pluggy                   0.13.0              
preshed                  3.0.9               
prettytable              3.10.0              
protobuf                 3.6.1               
prov                     1.5.2               
psutil                   5.5.1               
py                       1.8.1               
pyasn1                   0.4.2               
pyasn1-modules           0.2.1               
pycairo                  1.16.2              
pycosat                  0.6.3               
pycups                   1.9.73              
pydantic                 2.7.0               
pydantic-core            2.18.1              
pygments                 2.17.2              
PyGObject                3.36.0              
PyHamcrest               1.9.0               
PyJWT                    1.7.1               
pymacaroons              0.13.0              
PyNaCl                   1.3.0               
pyOpenSSL                19.0.0              
pyparsing                2.4.6               
pyRFC3339                1.1                 
pyrsistent               0.15.5              
pysam                    0.15.4              
pyserial                 3.4                 
pyteomics                4.7.1               
pytest                   4.6.9               
python-apt               2.0.0+ubuntu0.20.4.7
python-dateutil          2.9.0.post0         
python-debian            0.1.36ubuntu1       
pytz                     2024.1              
pyxdg                    0.26                
PyYAML                   5.3.1               
rdflib                   4.2.2               
rdflib-jsonld            0.4.0               
regex                    2023.12.25          
reportlab                3.5.34              
requests                 2.22.0              
requests-unixsocket      0.2.0               
rich                     11.2.0              
ruamel.yaml              0.17.21             
ruamel.yaml.clib         0.2.6               
safetensors              0.4.2               
schema-salad             5.0.20200220195218  
scipy                    1.9.0               
SecretStorage            2.3.1               
service-identity         18.1.0              
setuptools               45.2.0              
shellescape              3.4.1               
simplejson               3.16.0              
six                      1.14.0              
smart-open               6.4.0               
sos                      4.3                 
soupsieve                1.9.5               
spacy                    3.7.4               
spacy-legacy             3.0.12              
spacy-loggers            1.0.5               
SPARQLWrapper            1.8.5               
srsly                    2.4.8               
ssh-import-id            5.10                
sympy                    1.12                
systemd-python           234                 
thinc                    8.2.3               
tokenizers               0.15.2              
torch                    2.2.2               
tqdm                     4.66.2              
transformers             4.39.3              
triton                   2.2.0               
Twisted                  18.9.0              
typer                    0.9.4               
typing-extensions        4.11.0              
tzdata                   2024.1              
ubuntu-advantage-tools   8001                
ubuntu-drivers-common    0.0.0               
ufw                      0.36                
unattended-upgrades      0.1                 
urllib3                  1.25.8              
usb-creator              0.3.7               
wadllib                  1.3.3               
wasabi                   1.1.2               
wcwidth                  0.1.8               
weasel                   0.3.4               
webencodings             0.5.1               
wheel                    0.34.2              
xkit                     0.0.0               
xopen                    0.8.4               
zipp                     1.0.0               
zope.interface           4.7.1  
```

**Comment by yuz2011** [comment]
Hi,
In my view, I think that the error in question is not related to the environment. 
DeepFLR has already provided many demo data files, which should facilitate the direct execution of the problematic step (result_processing/DeepFLR_result_processing.py). Could you clarify whether executing this specific step directly using the files supplied by DeepFLR poses any issues?

Best regards,
Yu

**Comment by Arkadiy-Garber** [comment]
Hey Yu,

Sorry, it looks like I forgot to attach the demo folder that I've been working out of. I've been using the files that are in this folder, and the exact commands from the user guide. Are you not able to replicate the error on your end?

Here is the last error:
```

Traceback (most recent call last):
  File "result_processing/DeepFLR_result_processing.py", line 191, in <module>
    df["model_proteinsite"]=df.apply(combine,axis=1)
  File "/home/ark/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 3940, in __setitem__
    self._set_item_frame_value(key, value)
  File "/home/ark/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 4094, in _set_item_frame_value
    raise ValueError(
ValueError: Cannot set a DataFrame with multiple columns to the single column model_proteinsite

```
[demo_data.tar.gz](https://github.com/lmsac/DeepFLR/files/15180351/demo_data.tar.gz)

Thanks again,
Arkadiy

**Comment by yuz2011** [comment]
Hi Arkadiy,
Thank you for sharing the demo data and the code. Yes, I have used the demo data and code you provided but still was unable to replicate the error you mentioned. For all the codes in the repository, I've previously tested them for multiple times without issues. 
May I suggest a couple of things? It might help to keep only the necessary files, or alternatively, you could try using the files directly provided by DeepFLR to execute the step where the error occurs. Additionally, could you please confirm if the problematic step is python3 result_processing/DeepFLR_result_processing.py?

Best,
Yu
